### ISSUE TITLE
Add height and width properties to entities

### ISSUE THREAD

**Issue by EricTill** [EricTill/platformer#6]
Also need to reflect these changes in their renderer function (and a few other miscellaneous functions).

**Comment by MarcoAZ** [comment]
What's this for? Aren't they always the size of a tile?

**Comment by EricTill** [comment]
I'd like to have any size rectangle be possible! Actually I'm pretty sure the centered branch already does that - it's just the physics which is completely broken.

I have an idea for the physics. From the center, and each vertex draw a line to the potential new position. Use some fancy method of checking every edge of the background grid that line crosses and determine if it hits a wall somewhere. If so, handle that by 0-ing out velocity in that direction, and run the process over again from the new position with a new velocity vector.

That might be total overkill, though. But I was trying to think of something which would work for things moving really quickly and small objects like particles and whatnot.
